### ISSUE TITLE
Consider using alternative existing EventListener/Manager instead of own implementation

### ISSUE THREAD

**Issue by Koc** [doctrine/event-manager#19]

**Comment by Ocramius** [comment]
Closing here: the EVM we have is **very** simple and good enough for all use-cases related to persistence, and PSR-14 is still on its way.

Once that is through, and if the design for that is good enough, then we may consider pushing it again.

For now, it looks like PSR-14 supports stuff like stopping propagation, which doesn't look like a good fit for this component, as it complicates everything tenfold.
